language: python

install:
  # Install test dependencies
  - pip install tox --use-mirrors
  - pip install coveralls --use-mirrors

script: tox

env:
  global:
    # Envvars required for badge uploading
    - GH_REPO_SLUG=github.com/openphoto-python-badges/openphoto-python-badges
    - secure: "BQ57gUh+90CqCxerAkGg2GeVCyuoIzxtpCEBC26rBJZbWJQPVc7uI3ncWnyzcioulvyIk2CLnWJdv1TuPejFiqqZczkpXxK57rvOexerxhykQ26TSAdrTD0uyaVFWUjiw/oCXRc1vlvqfITj03ZNv/utF3DZmGrflKNGfakmjsQ="

after_success:
  # Send coverage results to coveralls.io
  - coveralls

after_script:
  # Install dependencies for BadBadger & Pylint
  - pip install pylint-patcher --use-mirrors
  - pip install GitPython --use-mirrors
  - pip install requests --use-mirrors
  - pip install requests-oauthlib --use-mirrors

  # Create Pylint badge
  - wget https://github.com/sneakypete81/badbadger/archive/master.zip
  - unzip master.zip
  - badbadger-master/scripts/badbadger custom

  # Run Pylint
  # Uses pylint-patcher to allow exceptions to be stored in a patchfile
  # (for information only, any errors don't affect the Travis result)
  # - pylint-patcher trovebox
